version: "3.8"

services:
  postgres:
    image: postgres:17-alpine
    container_name: goledger_challenge_db
    environment:
      POSTGRES_DB: goledger_challenge
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
